nuts_cracker/Admin/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('',views.AdminHomeView.as_view(),name='admin_index'),
  path('login',views.AdminLoginView.as_view(),name='admin_login'),
  path('logout',views.LogoutView.as_view(),name='admin_logout'),
  path('category/list&add',views.CategoryView.as_view(),name='category_list'),
  path('category/edit/<int:id>',views.CategoryUpdateView.as_view(),name='category_edit'),
  path('category/delete/<int:id>',views.CategoryDeleteView.as_view(),name='category_delete'),
  path('product/list',views.ProductView.as_view(),name='product_list'),
  path('product/add',views.AddProductView.as_view(),name='add_product'),
  path('product/edit/<int:pk>',views.ProductUpdateView.as_view(), name='edit_product'),
  path('product/delete/<int:pk>/',views.ProductDeleteView.as_view(), name='delete_product'),
  path('orders/new/list/',views.NewOrderListView.as_view(), name='new_orders'),
  path('orders/list/',views.OrderListView.as_view(), name='list_orders'),
  path('order/detail/<int:pk>/',views.OrderDetailView.as_view(), name='order_detail'),

]

nuts_cracker/Users/urls.py
from django.urls import path
from .import views

urlpatterns = [
  path('',views.MainDisplayView.as_view(), name='index'),
  path('auth/register/',views.UserRegisterView.as_view(), name='register'),
  path('auth/login/',views.UserLoginView.as_view(), name='login'),
  path('auth/logout/',views.UserLogoutView.as_view(), name='logout'),
  path('auth/forgot_password/',views.ForgotPasswordView.as_view(), name='forgot_password'),
  path('auth/reset_password/',views.ResetPasswordView.as_view(), name='reset_password'),
  path('auth/otp-verification/',views.OTPVerificationView.as_view(), name='otp_verification'),
  path('auth/resend_otp/',views.resend_otp, name='otp_resend'),
  path('save_profile/',views.ProfileFormView.as_view(), name='profile_form'),
  path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
  path('cart/list/',views.CartListView.as_view(),name='cart_list'),
  path('cart/add/<int:pk>/', views.AddToCartView.as_view(), name='add_to_cart'),
  path('cart/remove/<int:pk>/', views.RemoveCartItemView.as_view(), name='remove_cart'),
  path('wishlist/',views.WishlistView.as_view(), name='wishlist'),
  path('wishlist/add/<int:pk>/', views.AddToWishlistView.as_view(), name='add_to_wishlist'),
  path('wishlist/remove/<int:pk>/',views.RemoveFromWishlistView.as_view(), name='remove_from_wishlist'),
  path('ordernow/<int:pk>/',views.OrderNow.as_view(), name='order_now'),
  path('orderlist/',views.YourOrdersView.as_view(), name='your_orders'),
  path('checkout/',views.CheckoutView.as_view(), name='checkout'),

  path('non-existing-page/',views.non_existing_view, name='non_existing'),
]

nuts_cracker/nuts_cracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', include('Admin.urls')),
    path('', include('Users.urls')),
    path("super/", admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nuts_cracker/Users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta
import random
from Admin.models import Products
from django.core.validators import MinValueValidator, MaxValueValidator


class OTP(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="authenticate_by_otp"
    )
    code = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)
    used = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = str(random.randint(100000, 999999))
        super().save(*args, **kwargs)

    def is_valid(self):
        return not self.used and (timezone.now() - self.created_at).seconds < 300

    def __str__(self):
        return f"OTP for {self.user.username}- Code: {self.code}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.TextField()
    pin_code = models.CharField(max_length=10)
    mobile_number = models.CharField(max_length=15)

    def __str__(self):
        return f"{self.user.username}'s Profile"


class Cart(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    CART_STATUS_OPTIONS = (
        ("in-cart", "In Cart"),
        ("cancelled", "Cancelled"),
        ("order-placed", "Order Placed"),
    )
    status = models.CharField(
        max_length=100, default="in-cart", choices=CART_STATUS_OPTIONS
    )
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.product.title} ({self.quantity})"


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.product.title} - {self.user.username}"


class Order(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    ORDER_STATUS_OPTIONS = (
        ("dispatched", "Dispatched"),
        ("cancelled", "Cancelled"),
        ("order-placed", "Order Placed"),
        ("delivered", "Delivered"),
    )
    status = models.CharField(
        max_length=100, default="order-placed", choices=ORDER_STATUS_OPTIONS
    )
    PAYMENT_METHODS = (
        ("credit_card", "credit_card"),
        ("upi", "upi"),
        ("cash_on_delivery", "cash_on_delivery"),
    )
    payment_method = models.CharField(
        max_length=100, default="cash_on_delivery", choices=PAYMENT_METHODS
    )
    totel_price = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now_add=True)
    expected_delivery_date = models.DateTimeField(null=True, blank=True)
    delivery_at = models.DateTimeField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.date:
            self.date = timezone.now() 
        self.expected_delivery_date = self.date + timedelta(days=5)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Order for {self.product.title} ({self.status})"


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    PAYMENT_METHODS = (
        ("credit_card", "credit_card"),
        ("upi", "upi"),
        ("cash_on_delivery", "cash_on_delivery"),
    )
    payment_method = models.CharField(max_length=50, choices=PAYMENT_METHODS)
    payment_details = models.JSONField()  # For storing specific payment details
    created_at = models.DateTimeField(auto_now_add=True)

class Review(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200)
    rating = models.PositiveIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )

    def __str__(self):
        return (
            f"Review for {self.product.title} by {self.user.username} ({self.rating}/5)"
        )

nuts_cracker/Users/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.core.mail import send_mail
from django.contrib.auth import login, logout, authenticate
from .decorator import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseNotFound
import random
from django.utils import timezone
from django.contrib import messages
from django.conf import settings
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, FormView
from .forms import (
    UserRegisterForm,
    UserLoginForm,
    AddToCartForm,
    ProfileForm,
    ForgotPasswordForm,
    PasswordResetForm,
)
from django.contrib.auth.models import User
from Admin.models import Products
from .models import OTP, Cart, Order, Wishlist, Profile, Payment


# || CUSTOM VIEWS
def non_existing_view(request):
    return HttpResponseNotFound("This page does not exist.")


# SEND OTP
def send_otp(user, subject, message_template, recipient):
    # Get or create the OTP
    otp, created = OTP.objects.get_or_create(user=user)

    otp.code = str(random.randint(100000, 999999))
    otp.created_at = timezone.now()
    otp.used = False  # Reset the 'used' flag when a new OTP is generated
    otp.save()

    # Format the message with the OTP code
    message = message_template.format(otp_code=otp.code)

    send_mail(
        subject,
        message,
        settings.DEFAULT_FROM_EMAIL,
        recipient,
        fail_silently=False,
    )
    return otp.code


# || OTP VERIFICATIONS
class OTPVerificationView(View):
    def get(self, request):
        return render(request, "authentic/otp_verification.html")

    def post(self, request):
        otp_code = request.POST.get("otp_code")
        try:
            otp = OTP.objects.get(code=otp_code, used=False)
            if otp.is_valid():
                otp.used = True
                otp.save()

                user = otp.user
                user.is_active = True
                user.save()

                login(request, user)
                messages.success(request, "OTP verification successful.")

                # Get the redirect_url from the query parameters
                redirect_url = request.GET.get("redirect_url", "index")
                return redirect(redirect_url)
            else:
                messages.error(request, "Invalid OTP.\n Send new request")
                return redirect("otp_verification")

        except OTP.DoesNotExist:
            messages.error(request, "Invalid OTP")
            return redirect("otp_verification")


# Resend OTP CODE
def resend_otp(request):
    if request.method == "POST":  # Ensure it's a POST request
        user = request.user  # Get the currently logged-in user
        send_otp(
            user, "Your New OTP Code", "Your OTP code is {otp_code}.", [user.email]
        )
        messages.success(request, "A new OTP has been sent to your email.")
    else:
        messages.error(request, "Invalid request method.")

    return redirect("otp_verification")


#  || Main Page
class MainDisplayView(ListView):
    model = Products
    template_name = "main.html"
    context_object_name = "products"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Check if user is authenticated before querying Wishlist
        if self.request.user.is_authenticated:
            wishlist_products = Wishlist.objects.filter(
                user=self.request.user
            ).values_list("product", flat=True)
        else:
            wishlist_products = []

        context["wishlist_products"] = wishlist_products
        return context


#  || Authentiction Views


class UserRegisterView(CreateView):
    template_name = "authentic/registration.html"
    form_class = UserRegisterForm
    success_url = reverse_lazy("otp_verification")  # Default success URL

    def form_valid(self, form):
        user = form.save()
        if user:
            try:
                # Send OTP after successful registration
                send_otp(
                    user,
                    "Your OTP Code for Registering to Nutcracker",
                    "Hi,\nYour OTP code is: [{otp_code}].\n Valid for the next 5 minutes.\n Do not share this code with anyone",
                    [form.cleaned_data["email"]],
                )
                messages.success(self.request, "OTP has been sent to your email.")

                redirect_url = reverse("index")
                otp_url = f"{reverse('otp_verification')}?redirect_url={redirect_url}"
                return redirect(otp_url)

            except Exception as e:
                messages.error(self.request, "Connection required.")
                return redirect(self.request.META.get("HTTP_REFERER", "index"))

        # If user saving fails, fall back to default behavior
        return super().form_invalid(form)


class UserLoginView(FormView):
    template_name = "authentic/user_login.html"
    form_class = UserLoginForm

    def post(self, request, *args, **kwargs):
        uname = request.POST.get("username")
        psw = request.POST.get("password")
        user = authenticate(request, username=uname, password=psw)
        if user:
            login(request, user)
            try:
                # Send OTP
                send_otp(
                    user,
                    "Your OTP Code for Login",
                    "Hi,\nYour OTP code is: [{otp_code}].\n Valid for the next 5 minutes.\n Do not share this code with anyone",
                    [user.email],
                )
                messages.success(request, "OTP for verification is sent to your email")

                # Generate the redirect URL and pass it as a query parameter
                redirect_url = reverse("index")  # Reverse the URL for the 'index' view
                otp_verification_url = (
                    f"{reverse('otp_verification')}?redirect_url={redirect_url}"
                )

                return redirect(otp_verification_url)
            except Exception as e:
                messages.error(self.request, "Connection required.")
                return redirect(self.request.META.get("HTTP_REFERER", "index"))
        else:
            messages.error(request, "Invalid credentials")
            return redirect("login")

    # def post(self, request):
    #     uname = request.POST.get("username")
    #     psw = request.POST.get("password")
    #     user = authenticate(request, username=uname, password=psw)
    #     if user:
    #         login(request, user)
    #         messages.success(request, "Login Successful")
    #         return redirect("index")
    #     else:
    #         messages.success(request, "Invalid credaintials")
    #         return redirect("index")


@method_decorator(login_required, name="dispatch")
class UserLogoutView(View):
    def get(self, request):
        logout(request)
        messages.success(request, "Logout Successful")
        return redirect("index")


class ForgotPasswordView(FormView):
    template_name = "authentic/password_reset_request.html"
    form_class = ForgotPasswordForm

    def form_valid(self, form):
        username = form.cleaned_data["username"]
        email = form.cleaned_data["email"]
        user = User.objects.filter(username=username, email=email).first()
        if user:
            try:
                otp, created = OTP.objects.get_or_create(user=user)
                otp.code = str(random.randint(100000, 999999))
                otp.created_at = timezone.now()
                otp.used = False  # Reset the 'used' flag when a new OTP is generated
                otp.save()
                otp_url = f"{reverse('reset_password')}?otp_code={otp.code}&email={user.email}&username={username}"
                return redirect(otp_url)
            except:
                messages.error(self.request, "Connection requeared.")
                return redirect(self.request.META.get("HTTP_REFERER", "index"))
        else:
            messages.error(self.request, "User with this email does not exist.")
            return redirect("login")


class ResetPasswordView(FormView):
    template_name = "authentic/reset_password.html"
    form_class = PasswordResetForm

    def dispatch(self, request, *args, **kwargs):
        self.otp_code = request.GET.get("otp_code")  # Get the OTP code from the URL
        self.user_email = request.GET.get("email")
        self.username = request.GET.get("username")
        # get the user instences
        self.user = User.objects.filter(
            username=self.username, email=self.user_email
        ).first()
        if not self.user:
            messages.error(request, "User not found.")
            return redirect("forgot_password")

        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.user  # Pass the user instance to the form
        return kwargs

    def form_valid(self, form):
        otp = OTP.objects.filter(user=self.user, code=self.otp_code, used=False).first()
        if otp and otp.is_valid():
            self.user.set_password(
                form.cleaned_data["new_password1"]
            )  # Set the new password
            self.user.save()
            otp.used = True  # Mark the OTP as used
            otp.save()
            messages.success(self.request, "Your password has been reset successfully.")
            return redirect("login")  # Redirect to the login page
        else:
            messages.error(self.request, "Invalid or expired OTP.")
            return redirect("forgot_password")  # Redirect back to forgot password

    def form_invalid(self, form):
        return super().form_invalid(form)


# Profile Update view
@method_decorator(login_required, name="dispatch")
class ProfileFormView(FormView):

nuts_cracker/Users/templates/cart_list.html
{% extends 'index.html' %}
{% load static %}
{% load custom_filters %}

{% block main %}
<main class="container mt-5">
  <h2>Your Cart</h2>

  {% if cart_items %}

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product Title</th>
        <th class="text-secondary text-center">Quantity x Price</th>
        <th>Total Price</th>
        <th>Actions</th>
        <th>Buy</th>

      </tr>
    </thead>
    <tbody>
      {% for item in cart_items %}
      <form method="post" action="{% url 'add_to_cart' item.product.id %}">
        {% csrf_token %}
        <tr>
          <td class="d-flex aligned">
            {% if item.product.image and item.product.image.url|file_exists %}
            <img src="{{ item.product.image.url }}" alt="{{ item.product.title }}" style="width: 50px; height: auto;">
            {% else %}
            <img src="{% static 'img/placeholder.jpeg' %}" alt="Image not available" style="width: 50px; height: auto;">
            {% endif %}
          </td>
          <td class="fw-bold fs-5">{{ item.product.title }}</td>
          <td class="fw-bold fs-5 text-secondary text-center">

            <input type="number" min="1" name="quantity" value="{{ item.quantity }}" style="width: 50px; padding: 5px; border: none; border-radius: 5px; 
              box-shadow: inset 0 0 5px rgba(0,0,0,0.1); font-size: 14px;">
            <input type="hidden" name="item_id" value="{{ item.id }}">
            x {{ item.product.price }}

          </td>
          <td class="text-success fw-bold fs-5">{{ item.total_price|floatformat:2 }}</td>
          <td >
            <a href="{% url 'remove_cart' item.id %}" class="btn btn-danger btn-sm me-2"
               onclick="return confirm('Are you sure you want to remove this item from your cart?');">Delete</a>
            <button type="submit" class="btn btn-success btn-sm">Save</button>
          </td>
          <td>
            <a href="{% url 'order_now' item.product.id %}" class="btn btn-warning btn-sm">Order Now</a>
          </td>
          
          </tr>
      </form>
      {% endfor %}
    </tbody>
  </table>

  {% else %}
  <div class="empty-cart">
    <img src="{% static 'img/empty_cart.png' %}" alt="Empty cart" style="width: 300px; height: auto;">
    <h3>Oops! Your cart is empty</h3>
    <p>It looks like you haven't added anything to your cart yet.</p>
    <a href="{% url 'index' %}" class="btn btn-primary mt-3">Go to Shop</a>
  </div>
  <style>
    td {
      padding: 0;
    }

    .empty-cart {
      text-align: center;
      margin-top: 50px;
    }

    .empty-cart img {
      max-width: 100%;
      height: auto;
    }

    .empty-cart h3 {
      color: #333;
      margin-top: 20px;
    }

    .empty-cart p {
      color: #777;
      margin-bottom: 20px;
    }

    .empty-cart .btn-primary {
      padding: 10px 20px;
      font-size: 16px;
    }
  </style>
  {% endif %}
</main>
{% endblock main %}

nuts_cracker/Users/templates/confirm_profile.html
<h2>Confirm Your Address Details</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Confirm and Continue to Checkout</button>
</form>

nuts_cracker/Users/templates/index.html
{% extends 'base.html' %}
{% load static %}

  {% block title %}
  🥜Cracker | Precerve Your Food for a beter Days
  {% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<style>
  main {
    padding-top: 60px;
  }
</style>

{% endblock style %}

{% block header %}
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container-fluid d-flex align-items-center">

    <figure class="mb-0">
      <img width="60px" height="auto" class="navbar-logo rounded-circle" src="{% static 'img/wine_bottle.jpeg' %}"
        alt="NutCracker">
    </figure>
    <a class="navbar-brand ms-2" href="#">
      <h1 class="display-6 fw-bold mb-0">NutCracker</h1>
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav mx-auto mb-2 mb-lg-0 fw-bold">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Category</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Product</a>
        </li>
      </ul>

      <form class="d-flex" role="search">
        <input class="form-control me-0" type="search" placeholder="Search" aria-label="Search"
          style="border-radius: 0;">
        <button class="btn btn-outline-secondary" type="submit" style="border-radius: 0;">
          <span class="material-icons">search</span>
        </button>
      </form>

      <ul class="navbar-nav ms-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item me-3">
          <a href="{% url 'wishlist' %}" class="position-relative" style="text-decoration: none; color: inherit;">
            <span class="material-icons" style="font-size: 40px;">favorite</span>
            {% if wishlist_count > 0 %}
            <span class="badge bg-danger position-absolute top-1 start-100 translate-middle">{{ wishlist_count }}</span>
            {% endif %}
          </a>
        </li>
        <li class="nav-item me-3">
          <a href="{% url 'cart_list' %}" class="position-relative" style="text-decoration: none; color: inherit;">
            <span class="material-icons" style="font-size: 40px;">shopping_cart</span>
            {% if cart_count > 0 %}
            <span class="badge bg-danger position-absolute top-1 start-100 translate-middle">{{ cart_count }}</span>
            {% endif %}
          </a>
        </li>
        {% else %}
        <li class="nav-item"><a class="btn btn-dark px-2 fw-bold me-2" href="{% url 'register' %}">Sign Up</a></li>
        <li class="nav-item"><a class="btn btn-outline-dark px-2 fw-bold me-2" href="{% url 'login' %}">Sign In</a></li>
        {% endif %}
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle fw-bold fs-5 d-flex align-items-center" href="#" id="navbarDropdown"
            role="button" data-bs-toggle="dropdown" aria-expanded="false"><span
              class="material-icons text-success fs-2">manage_accounts</span> {{ request.user }}</a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item d-flex align-items-center fw-bold" href="{% url 'profile_form' %}"><span
                  class="material-icons text-success me-2">verified</span>Your Profile</a></li>
            <li>
            <li><a class="dropdown-item d-flex align-items-center fw-bold" href="{% url 'your_orders' %}"><span
                  class="material-icons text-warning me-2">
                  low_priority
                </span>Your Orders</a></li>
            <li>
              <a class="dropdown-item d-flex align-items-center fw-bold" href="{% url 'logout' %}"><span
                  class="material-icons fw-bold text-danger me-2">logout</span>LogOut</a>
            </li>
          </ul>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
{% endblock header %}

{% block main %}

{% endblock main %}

nuts_cracker/Users/templates/order_success.html
{% extends 'index.html' %}
{% load static %}

{% block main %}
<div class="container mt-5">
    <div class="alert text-center" style="border: none;">
        <h2 class="mb-3 text-success">Order Placed Successfully!</h2>
        <img src="{% static 'img/success_order.png' %}" alt="Success Order" class="img-fluid mb-3" style="width: 300px; height: auto;">
        <p class="fs-5">Thank you for your order. We will notify you once it is confirmed.</p>
        <a href="{% url 'index' %}" class="btn btn-primary btn-lg">Return to Home</a>
    </div>
</div>
{% endblock %}

nuts_cracker/Users/templates/orderlist.html
{% extends 'index.html' %}
{% load static %}
{% load custom_filters %}

{% block main %}
<div class="container mt-5">
  <h1 class="mb-4">Your Orders</h1>

  {% if orders %}
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Image</th>
          <th>Product</th>
          <th>Status</th>
          <th>Total Price</th>
          <th>Payment Method</th>
          <th>Date</th>
          <th>Expected Delivery Date</th>
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
        <tr>
         
          <td>
            {% if order.product.image and order.product.image.url|file_exists %}
            <img src="{{ order.product.image.url }}" alt="{{ order.product.title }}"
                style="width: 50px; height: auto;">
            {% else %}
            <img src="{% static 'img/placeholder.jpeg' %}" alt="Image not available"
                style="width: 50px; height: auto;">
            {% endif %}
        </td>

          <td>{{ order.product.title }}</td>
          <td>
            {% if order.status == 'cancelled' %}
            <span class="badge bg-danger">{{ order.get_status_display }}</span>
            {% elif order.status == 'dispatched' %}
            <span class="badge bg-warning">{{ order.get_status_display }}</span>
            {% elif order.status == 'delivered' %}
            <span class="badge bg-success">{{ order.get_status_display }}</span>
            {% else %}
            <span class="badge bg-info">{{ order.get_status_display }}</span>
            {% endif %}
          </td>
          <td>₹{{ order.totel_price }}</td>
          <td>{{ order.get_payment_method_display }}</td>
          <td>{{ order.date|date:"F j, Y, g:i a" }}</td>
          <td>{{ order.expected_delivery_date|date:"F j, Y" }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
  <div class="d-flex flex-column align-items-center justify-content-center text-center mt-5">
    <img src="{% static 'img/empty-orders-image.png' %}" alt="No Orders" style="width: 300px; height: auto; margin-bottom: 15px;"> <!-- Increased size -->
    <h5 class="m-0 fs-4">No Orders Yet!</h5>
    <p  class="m-0 fs-5">It looks like you haven't placed any orders. Start shopping now!</p>
    <a href="{% url 'index' %}" class="btn btn-info" style="margin-top: 10px;">Go to Shop</a>
</div>

{% endif %}
</div>
{% endblock %}

nuts_cracker/Users/templates/product_detail.html
{% extends 'index.html' %}
{% load static %}
{% load custom_filters %}

{% block main %}

<main class="container mt-5">
  <div class="row">
    <div class="col-md-6">

      {% if product.image and product.image.url|file_exists %}
      <img src="{{ product.image.url }}" class="img-fluid" alt="{{ product.title }}"
        style="width: auto; height: 100%; object-fit: cover;">
      {% else %}
      <img src="{% static 'img/placeholder.jpeg' %}" class="img-fluid" alt="Image not available"
        style="width: auto; height: 100%; object-fit: cover;">
      {% endif %}

    </div>
    <div class="col-md-6">
      <h1 class="mb-3">{{ product.title }}</h1>
      <p>{{ product.description }}</p>
      <p class="text-secondary p-0 m-0">MRP: <s>{{ product.mrp }} <span class="material-icons fs-6">currency_rupee</span></s></p>
      <p class="p-0 mb-2 text-success fw-bold  d-flex align-items-center fs-4">
        <span><span class="text-secondary">Price:</span> {{ product.price }} </span>
        <span class="material-icons">currency_rupee</span>
      </p>
      <div class="rating mb-3 d-flex align-items-center">
        <span class="material-icons" style="color: green;">star</span>
        <strong>4.5</strong>
      </div>

      <form action="{% url 'add_to_cart' product.id %}" method="post">
        {% csrf_token %}
        <p class="d-flex align-items-center fs-4">Pack of: {{ form.quantity }}</p>

        <div class="d-flex gap-3">
          <button type="submit" name="action" value="add_to_cart" class="btn btn-warning">Add to Cart</button>
        </div>
      </form>

    </div>
  </div>
</main>

{% endblock main %}